config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  as :user do
  get "/login" => "devise/sessions#new"
end
  resources :companies
  resources :themes 
  root 'home#index'
  get '/users/:id' => 'users#show', as: :user
  
end

app/models/company.rb
class Company < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :theme
  	# is_sluggable :subdomain
	has_attached_file :logo, :styles => { :large => "300x300", :medium => "150x150>", :small => "100x100", :thumb => "75x75>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :logo, :content_type => /\Aimage/
	validates_attachment_file_name :logo, :matches => [/png\Z/, /jpe?g\Z/]
	do_not_validate_attachment_file_type :logo
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_one :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, 
		   :validatable, :rememberable, :trackable


	# validates :first_name, presence: true
	# validates :last_name, presence: true
	# validates :phone, phone_number: true
	has_one :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :last_name, :phone, :email, :password) }
  end
   def after_sign_in_path_for(resource)
  	companies_path(resource)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_user!, only: [:index]

	before_action :set_company, only: [:destroy, :show, :update]

	def index
		@company = current_user.company
		@theme = @company.theme.theme_name
	end

	def show
	@theme = @company.theme.theme_name
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params) 
		@company.user = User.find(current_user.id)
		@company.save
  		redirect_to new_theme_path notice: "New Page Created!"
	end

	def update
		if @company.update(company_params)
	  		respond_to do |format|
	  			format.html { redirect_to @company.project, notice: 'Site successfully updated.' }
	      		format.json { respond_with_bip(@company) }
	  		end
	  	else
	  		respond_to do |format|
	  			format.html { redirect_to @company.project, notice: 'Something went wrong.' }
	      		format.json { respond_with_bip(@company) }
	  		end
	  	end
	end

	def destroy

		if @company.destroy
			flash[:notice] = "Site Deleted!"
			redirect_to "/users/:id"
		else
			flash[:notice] = "Could not delete. Sorry."
			redirect_to "/users/:id"
		end
	end

	private

	def set_company
		if params[:id].length < 3
			@company = Company.find(params[:id])
		else
			@company = Company.find_by_subdomain(params[:id])
		end
	end
	
	def company_params
		params.require(:company).permit( :company, :tagline, :address1, :address2, :city, :state, :zipcode, :phone, :fax, :email, :about, :hours, :year_established, :facebook, :twitter, :tumblr, :linkedin, :package_id, :template_id, :user_id, :subdomain, :logo)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected
	def after_sign_up_path_for(resource)
		new_company_path(resource)
	end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
	def index
	end

	def new
		@theme = Theme.new
	end
	def create
		@theme = Theme.new(theme_params)
		@theme.save
		@update_theme = current_user.company.update(theme_id: @theme.id)
		redirect_to companies_path
	end

	private

	def theme_params 
	params.require(:theme).permit(:theme_name, :theme_id)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show
	end

  private
  def set_company
    if params[:id].length < 3
      @company = Company.find(params[:id])
    else
      @company = Company.find_by_subdomain(params[:id])
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<div class="container">
<div class = "header-<%= @theme %>">
<div class="company-<%= @theme  %>">
	<p class="flash-notice">Psssst...You're in edit mode! click to change any field.</p>
	<h1><%=best_in_place  @company, :company, type: :input %></h1>
</div>

<div class="tagline-<%= @theme  %>">
	<h3><%=best_in_place @company, :tagline, type: :input  %></h3>
</div>
</div>
<div class="grid-items grid-colors">
  <a href="javascript:void(0)" class="grid-item show">
    <i class="fa fa-phone-square fa-3x"></i>
   <h1>Contact Us</h1>
    <p><%=best_in_place @company, :phone, type: :input%></p>
    <p><%= best_in_place @company, :fax, type: :input%></p>
     <p><%= best_in_place @company, :email, type: :input%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image show">
 <i class="fa fa-heart fa-3x"></i>
  <h1>About Us</h1>
    <p><%=best_in_place @company, :about, type: :textarea%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big show">
  <i class="fa fa-map-marker fa-3x"></i>
    <h1>Find Us</h1>
    <p><%=best_in_place @company, :address1, type: :input%></p>
     <p><%=best_in_place @company, :address2, type: :input%></p>
     <p><%=best_in_place @company, :city, type: :input%>, <%=@company.state%></p>
      <p><%=best_in_place @company, :zipcode, type: :input%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item show">
    <i class="fa fa-clock-o fa-3x"></i>
    <h1>Our Hours</h1>
    <p><%= best_in_place @company, :hours, type: :input %></p>
  </a>
  <a href="javascript:void(0)" class="grid-item show">
   <i class="fa fa-user fa-3x"></i>
    <h1>Social</h1>
    <p href="<%= @company.facebook  %>" title="">Facebook</p>
    <p href="<%= @company.twitter  %>" title="">Twitter</p>
     <p href="<%= @company.linkedin  %>" title="">Linkedin</p>
      <p href="<%= @company.tumblr  %>" title="">Tumblr</p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image show">
   <iframe width="600" height="150" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=<%= @company.address1 %> <%= @company.city %> <%= @company.state %> <%= @company.zipcode %>&output=embed"></iframe>
  </a>
</div>
</div>

app/views/companies/new.html.erb
  <div class="container">
    <div class="hero formhero">
      <div class="hero-inner">
        <div class="hero-copy">
          <h2>Enter Information to Create Your Business Page</h2>
        </div>
      </div>
    </div>
    <div class="form">
      <%= form_for @company, :html => { :multipart => true } do |f| %>
        
        <% if @company.errors.any? %>
          <ul>
            <% @company.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="field">
          <%= f.label :company %>
          <%= f.text_field :company, autofocus: true %>
        </div>

         <div class="field">
          <%= f.label :subdomain %>
          <%= f.text_field :subdomain %>
        </div>

        <div class="field">
          <%= f.label :tagline %>
          <%= f.text_field :tagline%>
        </div>

         <div class="field">
          <%= f.label :address1 %>
          <%= f.text_field :address1%>
        </div>

         <div class="field">
          <%= f.label :address2 %>
          <%= f.text_field :address2%>
        </div>

         <div class="field">
          <%= f.label :city %>
          <%= f.text_field :city%>
        </div>

         <div class="field">
          <%= f.label :state %>
          <%= f.text_field :state%>
        </div>

         <div class="field">
          <%= f.label :zipcode %>
          <%= f.text_field :zipcode%>
        </div>

         <div class="field">
          <%= f.label :phone %>
          <%= f.telephone_field :phone%>
        </div>
   
        <div class="field">
          <%= f.label :fax %>
          <%= f.telephone_field :fax%>
        </div>

   </div>

    <div class="form">

        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email%>
        </div>

        <div class="field">
          <%= f.label :about %>
          <%= f.text_area :about%>
        </div>
        
        <div class="field">
          <%= f.label :hours %>
          <%= f.text_field :hours%>
        </div>

        <div class="field">
          <%= f.label :year_established %>
          <%= f.text_field :year_established%>
        </div>

        <div class="field">
          <%= f.label :facebook %>
          <%= f.url_field :facebook%>
        </div>

        <div class="field">
          <%= f.label :twitter %>
          <%= f.url_field :twitter%>
        </div>

        <div class="field">
          <%= f.label :tumblr %>
          <%= f.url_field :tumblr%>
        </div>

        <div class="field">
          <%= f.label :linkedin %>
          <%= f.url_field :linkedin%>
        </div>

        <div class="field">
          <%= f.label :logo %>
          <%= f.file_field :logo %>
        </div>

        <div class="actions" align="center">
          <%= f.submit "Create Site" %>
        </div>
        <% end %>
    </div>
  </div>

app/views/companies/show.html.erb
<% if current_user.company.theme.theme_name == "Resturant" %>
<% content_for :head do %>
  <title><%= @company.company %> in <%= @company.city  %>, <%= @company.state  %></title>
  <meta name="description" content="<%=h truncate(@company.about, :length => 155) %>">
 <% end %>
<div class = "header-<%= @theme %>">
<div class="company-<%= @theme  %>">
	<h1><%= @company.company %></h1>
</div>

<div class="tagline-<%= @theme  %>">
	<h3><%=@company.tagline  %></h3>
</div>
</div>

<div class="container">
<div class="info-<%= @theme  %>">
<h2>Find Us</h2>
<div class="address1-<%= @theme  %>">
	<%= @company.address1  %>
</div>

<div class="address1">
	<h6>Address 2: </h6><%= @company.address2 %>
</div>
<div class="city-<%= @theme  %>">
	<h6>City: </h6><%= @company.city %>
</div>
<div class="state-<%= @theme  %>">
	<h6>State: </h6><%= @company.state %>
</div>
<div class="zipcode-<%= @theme  %>">
	<h6>Zipcode: </h6><%= @company.zipcode %>
</div>
</div>
<div class="info-<%= @theme  %>">
<h2>Contact Us</h2>
<div class="phone-<%= @theme  %>">
	<%= @company.phone  %>
</div>
<div class="fax-<%= @theme  %>">
	<%= @company.fax %>
</div>
<div class="email-<%= @theme  %>">
	 <%= @company.email %>
</div>
<div class="hours-<%= @theme  %>">
	<%= @company.hours %>
</div>
</div>
<div class="info-<%= @theme  %>">
<h2>Hours</h2>
<div class="hours-<%= @theme  %>">
	<%= @company.hours  %>
</div>
</div>
</div>
<% end %>

<% if current_user.company.theme.theme_name == "Milano" %>
<div class="container">
<div class = "header-<%= @theme %>">
<div class="company-<%= @theme  %>">
	<h1><%= @company.company %></h1>
</div>

<div class="tagline-<%= @theme  %>">
	<h3><%=@company.tagline  %></h3>
</div>
</div>
<div class="grid-items">
  <a href="javascript:void(0)" class="grid-item">
    <i class="fa fa-phone-square fa-3x"></i>
   <h1>Contact Us</h1>
    <p><%=@company.phone%></p>
     <p><%=@company.fax%></p>
     <p><%=@company.email%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image">
 <i class="fa fa-heart fa-3x"></i>
  <h1>About Us</h1>
    <p><%=@company.about%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big">
  <i class="fa fa-map-marker fa-3x"></i>
    <h1>Find Us</h1>
    <p><%=@company.address1%></p>
     <p><%=@company.address2%></p>
     <p><%=@company.city%>, <%=@company.state%></p>
      <p><%=@company.zipcode%></p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <i class="fa fa-clock-o fa-3x"></i>
    <h1>Our Hours</h1>
    <p><%= @company.hours %></p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
   <i class="fa fa-user fa-3x"></i>
    <h1>Social</h1>
    <p href="<%= @company.facebook  %>" title="">Facebook</p>
    <p href="<%= @company.twitter  %>" title="">Twitter</p>
     <p href="<%= @company.linkedin  %>" title="">Linkedin</p>
      <p href="<%= @company.tumblr  %>" title="">Tumblr</p>
  </a>
  <a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image">
   <iframe width="600" height="150" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=<%= @company.address1 %> <%= @company.city %> <%= @company.state %> <%= @company.zipcode %>&output=embed"></iframe>
  </a>
</div>
</div>
<% end %>

app/views/home/index.html.erb
<div class="hero">
	<div class="hero-inner">
		<div class="hero-copy">
			<h1>Local</h1>
			<p>The easiest way to set your your businesses web precense</p>	
		</div>
    <button class="signup_button"><%= link_to "Sign Up Now", new_user_registration_path %></button>
	</div>
</div>
</div>
<div class="grid-items-lines">
  <a href="javascript:void(0)" class="grid-item">
    <i class="fa fa-money fa-3x"></i>
    <h1>Free Websites</h1>
    <p>Build your webside, and share your ideas <i>For free</i> .</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
  <i class="fa fa-picture-o fa-3x"></i>
    <h1>Choose Your theme</h1>
    <p>Select from our beautiful themes, choose the one that best speaks to your buisness.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
  <i class="fa  fa-pie-chart fa-3x"></i>
    <h1>Better SEO</h1>
    <p>add your own key words and descriptions to help users better find you</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
   <i class="fa fa-pencil-square-o fa-3x"></i>
    <h1>Edit content</h1>
    <p>Edit your content right in the place it falls on the page, instant ideas, instant results</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
   <i class="fa  fa-mobile fa-3x"></i>
    <h1>Mobile friendly</h1>
    <p>all of our themes are mobile friendly. So your website looks great on the go too.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <i class="fa fa-check-square fa-3x"></i>
    <h1>Easy to use</h1>
    <p>We can have you up in under 10 minutes, each time. every time. </p>
  </a>
  <div class="right-cover"></div>
  <div class="bottom-cover"></div>
</div>
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer -- This was made by very cool people.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for?(:head) %>
  	<%= yield(:head) %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render partial: 'shared/nav'  %>
	<% if notice %> <p class="notice"><%= notice %></p> <% end %>
    <% if alert %> <p class="alert"><%= alert %></p> <% end %>

<%= yield %>
</body>
</html>

app/views/shared/_nav.html.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <i class="fa fa-code fa-2x"></i>
    </a>
    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"> <%= link_to "Home", root_path%></li>
        </li>
      </ul>
    </div>
    <div class="navigation-tools"> 
     <% if current_user %>
       <%= link_to "Sign Out", destroy_user_session_path, class: :sign_out, method: :delete %>
       <%= link_to "My Account", user_path(current_user.id), class: :sign_out %>
        <% if current_page? companies_path %>
            <%= link_to "View My Site", company_path(current_user.company.subdomain), class: :sign_up%>
        <% else %>
            <%= link_to "Edit My Site", companies_path, class: :sign_up %>
        <% end %>
            <%= link_to "Delete My Site", user_path(current_user.id), class: :sign_out, method: :delete, data: {confirm: 'Are you sure?'} %>
    <% else %>
            <%= link_to "Sign In", new_user_session_path, class: :sign_in %> 
            <%= link_to "Sign Up", new_user_registration_path, class: :sign_up %>
    <% end %>
    </div>
  </div>
</header>

app/views/themes/index.html.erb
<h1>index</h1>

app/views/themes/new.html.erb
<div class="section-header">
	<h1>Select a theme for your website</h1>
</div>
<div class="cards">
	<div class="card">
		<div class="card-image">
			<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
		</div>
		<div class="card-header">
			Resturant
		</div>
		<div class="card-copy">
			<p>A theme based around good food.</p>
		</div>
		<div class="card-stats">
			<%= form_for @theme do |f|  %>
			<input type="hidden" id="theme_theme_name" name="theme[theme_name]" value="Resturant">
			<%= f.submit  %>
			<% end %>
		</div>
	</div>
	<div class="card">
		<div class="card-image">
			<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-4.png" alt="">
		</div>
		<div class="card-header">
			Nuve
		</div>
		<div class="card-copy">
			<p>A modern theme for a modern buisness</p>
		</div>
		<div class="card-stats">
			<%= form_for @theme do |f|  %>
			<input type="hidden" id="theme_theme_name" name="theme[theme_name]" value="Nuve">
			<%= f.submit  %>
			<% end %>
		</div>
	</div>
	<div class="card">
		<div class="card-image">
			<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-3.png" alt="">
		</div>
		<div class="card-header">
			Milano
		</div>
		<div class="card-copy">
			<p>Just like the cookie, this theme is delicious</p>
		</div>
		<div class="card-stats">
			<%= form_for @theme do |f|  %>
			<input type="hidden" id="theme_theme_name" name="theme[theme_name]" value="Milano">
			<%= f.submit  %>
			<% end %>
		</div>
</div>
</div>

app/views/users/index.html.erb
<div class="">
<h1>Hi, <%= current_user.first_name %> welcome to your user page</h1>
<p>From here you have a couple of options. Make a choice below</p>
<div class="">
<ul>
	<li><%= link_to('Edit registration', edit_user_registration_path(@user),class: :button) %>
	<%= link_to "Edit My Site", companies_path, class: :button %></li>
	<li></li>
	<li></li>
</ul>
</div>

</div>

app/views/users/show.html.erb
<div class="container" align="center">
	<h1>Hi, <%= current_user.first_name %>! Welcome To Your User Page.</h1>
	<p>From here you have a couple of options. Make a choice below</p>
	<div class="cards">
		<div class="card" align="center">
			<div class="card-image">
				<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
			</div>
			<div class="card-header" >
				<%= link_to 'Edit User', edit_user_registration_path(@user) %>
			</div>
		</div>
		<div class="card" align="center">
			<div class="card-image">
				<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
			</div>
			<div class="card-header">
				<%= link_to 'View My Site', company_path(current_user.company.subdomain) %>
			</div>
		</div>
		<div class="card" align="center">
			<div class="card-image">
				<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
			</div>
			<div class="card-header">
				<%= link_to "Create New Site", new_company_path %>
			</div>
		</div>
	</div>
</div>